# Generated by Django 5.2.5 on 2025-12-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TO_do', '0002_item_todolist_delete_ppl_item_todolist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='complex',
            new_name='complete',
        ),
    ]
